services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 6000:5432
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:    